---
template:
  files:
    - file: "Output PYTHON"
      input: template_python.j2
      output: "{{dest_file}}2.py"
    - file: "Output other PYTHON"
      input: template_python3.j2
      output: "{{dest_file}}3.py"

