---
template:
  files:
    - file: "Header file"
      input: template_gcc_h.j2
      output: "{{dest_file}}.h"
    - file: "Code file"
      input: template_gcc_c.j2
      output: "{{dest_file}}.c"
      echo:
        - "gcc -c {{dest_file}}.c -DUNIT_TEST"
    - file: "Action file"
      input: template_gcc_a.j2
      preload: "{{dest_file}}.action.c"
      output: "{{dest_file}}.action.c"
      echo:
        - "gcc -c {{dest_file}}.action.c -DUNIT_TEST"
