---
template:
  files:
    - file: "Header file"
      input: template_gcc_h.j2
      output: "{{dest_file}}3.h"
    - file: "Code file"
      input: template_gcc_c.j2
      output: "{{dest_file}}3.c"
      echo:
        - "gcc -c {{dest_file}}3.c -DUNIT_TEST"
    - file: "Action file"
      input: template_gcc_a.j2
      preload: "{{dest_file}}3.skel.c"
      output: "{{dest_file}}3.skel.c"
      echo:
        - "gcc -c {{dest_file}}3.skel.c -DUNIT_TEST"
